apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets/ClusterSecretStore.yaml
  - secrets/ExternalSecret.yaml
  - ../agent/
  - ../db/
  - ../be/
  - ../fe/
  - ../es/
  - ../kibana/


