apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/
- agent/
- db/
- be/
- fe/
- es/
images:
- name: kubi-agent
  newName: asia-south1-docker.pkg.dev/stone-fortress-338918/kubi-repo/kubi-agent
  newTag: main-a0aa7f8b
- name: kubi-backend
  newName: asia-south1-docker.pkg.dev/stone-fortress-338918/kubi-repo/kubi-backend
  newTag: main-a0aa7f8b
- name: kubi-frontend
  newName: asia-south1-docker.pkg.dev/stone-fortress-338918/kubi-repo/kubi-frontend
  newTag: main-a0aa7f8b
