apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/
- agent/
- db/
- be/
- fe/
- es/
images:
- name: kubi-agent
  newName: shubhamthokare/kubi-agent
  newTag: main-76ad9c31
- name: kubi-backend
  newName: shubhamthokare/kubi-backend
  newTag: main-76ad9c31
- name: kubi-frontend
  newName: shubhamthokare/kubi-frontend
  newTag: main-76ad9c31
