{{- if .Values.mongodb.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubi.fullname" . }}-mongodb
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "kubi.labels" . | nindent 4 }}
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kubi.selectorLabels" . | nindent 6 }}
      component: database
  template:
    metadata:
      labels:
        {{- include "kubi.selectorLabels" . | nindent 8 }}
        component: database
    spec:
      containers:
      - name: mongodb
        image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
        imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mongodb.service.port }}
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: {{ include "kubi.fullname" . }}-mongodb-pvc
{{- end }}
