apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubi-external-secrets
  namespace: kubi
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: kubi-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: DB_PASSWORD
    - secretKey: RESEND_API_KEY
      remoteRef:
        key: RESEND_API_KEY
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: JWT_SECRET_KEY
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: GEMINI_API_KEY
    - secretKey: GITLAB_TOKEN
      remoteRef:
        key: GITLAB_TOKEN
    - secretKey: ARIZE_SPACE_ID
      remoteRef:
        key: ARIZE_SPACE_ID
    - secretKey: ARIZE_API_KEY
      remoteRef:
        key: ARIZE_API_KEY
    - secretKey: SSO_CLIENT_ID
      remoteRef:
        key: SSO_CLIENT_ID
    - secretKey: SSO_CLIENT_SECRET
      remoteRef:
        key: SSO_CLIENT_SECRET
