apiVersion: v1
kind: Secret
metadata:
  name: kubi-secrets
  namespace: kubi
type: Opaque
stringData:
  GEMINI_API_KEY: "AIzaSyD4RvKrGsNxLrIlW-0eac396RtapLG-hWk"
  GITLAB_TOKEN: "glagent-qPzbUCx0PmrA9XI0kd9agGM6MQpvOjEKcDoxZDF0bWUQ.01.181qrmoeh"
  ARIZE_SPACE_ID: "U3BhY2U6NDQ3NzA6dE1nZA=="
  ARIZE_API_KEY: "ak-74f52854-3783-487e-8a4f-95044e2438f6-ZZSpSdxIWK7KhA0wHO4oLEdADPICzM43"
