apiVersion: v1
kind: Secret
metadata:
  name: kubi-secrets
  namespace: kubi
  labels:
    app: kubi
    secrets-mode: local
type: Opaque
stringData:
  DB_PASSWORD: dummy
  RESEND_API_KEY: dummy
  JWT_SECRET_KEY: dummy
  GEMINI_API_KEY: dummy
  GITLAB_TOKEN: dummy
  ARIZE_SPACE_ID: dummy
  ARIZE_API_KEY: dummy
  SSO_CLIENT_ID: dummy
  SSO_CLIENT_SECRET: dummy
