apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubi

secretGenerator:
  - name: kubi-secrets
    envs:
      - .env.local

generatorOptions:
  disableNameSuffixHash: true
