apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: kubi
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.13.2
          ports:
            - containerPort: 5601
              name: ui
              protocol: TCP
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch-service:9200"
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /login
              port: 5601
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /login
              port: 5601
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 3
