apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: kubi
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.13.2
          ports:
            - containerPort: 5601
              name: ui
              protocol: TCP
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch-service:9200"
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /login
              port: 5601
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /login
              port: 5601
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 5
            timeoutSeconds: 5
