apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubi.fullname" . }}-config
  namespace: {{ .Values.namespace | default .Release.Namespace }}
data:
  MONGODB_URL: "mongodb://{{ include "kubi.fullname" . }}-mongodb-service:{{ .Values.mongodb.service.port }}"
  DATABASE_NAME: {{ .Values.backend.env.databaseName | quote }}
  BACKEND_URL: "http://{{ include "kubi.fullname" . }}-backend-service:{{ .Values.backend.service.port }}"
