apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubi.fullname" . }}-secrets
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  GEMINI_API_KEY: {{ .Values.backend.env.geminiApiKey | quote }}
  GITLAB_WEBHOOK_TOKEN: {{ .Values.backend.env.gitlabWebhookToken | quote }}
