apiVersion: v1
kind: ConfigMap
metadata:
  name: kubi-config
  namespace: kubi
data:
  BACKEND_URL: "http://kubi-backend-service:8000"
  AGENT_URL: "http://kubi-agent-service:8080"
  FRONTEND_URL: "http://kubi.kontactless.in"
