apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/
  - ingress.yaml

images:
  - name: kubi-agent
    newName: kubi-agent
    newTag: latest
  - name: kubi-backend
    newName: kubi-backend
    newTag: latest
  - name: kubi-frontend
    newName: kubi-frontend
    newTag: latest
