apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubi

resources:
  - ../../base/
  - ../../secrets/local/
  # ingress.yaml removed - using local nginx Docker container instead (local-dev/)

patches:
  - path: configmap-patch.yaml

images:
  - name: kubi-agent
    newName: kubi-agent
    newTag: latest
  - name: kubi-backend
    newName: kubi-backend
    newTag: latest
  - name: kubi-frontend
    newName: kubi-frontend
    newTag: latest

generatorOptions:
  disableNameSuffixHash: true
