apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubi-backend
  namespace: kubi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubi-backend
  template:
    metadata:
      labels:
        app: kubi-backend
    spec:
      serviceAccountName: kubi-backend-sa
      containers:
      - name: backend
        image: kubi-backend:latest # Build this from be/Dockerfile
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: kubi-secrets
              key: GEMINI_API_KEY
        - name: GITLAB_WEBHOOK_TOKEN
          valueFrom:
            secretKeyRef:
              name: kubi-secrets
              key: GITLAB_WEBHOOK_TOKEN
        - name: MONGODB_URL
          valueFrom:
            configMapKeyRef:
              name: kubi-config
              key: MONGODB_URL
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: kubi-config
              key: DATABASE_NAME
        ports:
        - containerPort: 8000
