# GitLab Agent configuration for Kubi Platform
gitops:
  manifest_projects:
    - id: kubi-agent/kubi
      paths:
        - glob: 'deploy/manifests/hydrated.yaml'
observability:
  logging:
    level: debug
