apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubi.fullname" . }}-frontend
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "kubi.labels" . | nindent 4 }}
    component: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubi.selectorLabels" . | nindent 6 }}
      component: frontend
  template:
    metadata:
      labels:
        {{- include "kubi.selectorLabels" . | nindent 8 }}
        component: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        env:
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "kubi.fullname" . }}-config
              key: BACKEND_URL
        ports:
        - containerPort: {{ .Values.frontend.service.port }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
